### ISSUE TITLE
path_forward possible issue

### ISSUE THREAD

**Issue by KyleAlt2021** [ajoshua01/AI-TSP#2]
Whenever I use path_forward in a test situation, it seems the value given for the 'distance traveled' is ALWAYS the same value as the node values. Every time. I'm not sure what the cause is.

Example: I travel to node 5 from 3.
The 'distance traveled' is absolutely, every single time, either a value of 3 or 5

Example 1:
![examplepicture1](https://user-images.githubusercontent.com/73610654/116005791-82255080-a5d6-11eb-93ee-1fd2a55cb808.PNG)

Example 2:
![examplepicture2](https://user-images.githubusercontent.com/73610654/116005796-8487aa80-a5d6-11eb-9ad8-bf6604f120d6.PNG)

Code example:
![examplepicture3](https://user-images.githubusercontent.com/73610654/116005802-87829b00-a5d6-11eb-97a1-d81fef150b53.PNG)

Maybe this is an issue on my end? But I figured I would raise it while I am moving along on the algorithm.

**Comment by ajoshua01** [comment]
sorry man I didn't see that this was here. Let me look

hmm its weird because I'm not getting this issue.

graph.Path_forward(1) always yields a somewhat different result. Are you using the most recent version of the graph class?

When you say distance traveled? What are you referring to?


oh I think I understand the issue. So the "Step: " is not indicating the value of distance traveled but which path you've chosen. So among the available node edges you are stepping to option 3. I can make that more clear.

So, since you're stepping each time at path_forward(3) it will keep printing "Step: 3."

**Comment by ajoshua01** [comment]
hmm its weird because I'm not getting this issue. 

graph.Path_forward(1) always yields a somewhat different result. Are you using the most recent version of graph class

**Comment by ajoshua01** [comment]
When you say distance traveled? What are you referring to?

**Comment by KyleAlt2021** [comment]
Oh, that's no problem. What I was seeing is that in the phrase "Travel x km from node y to node z" is that X is ALWAYS the same value as either Y or Z, if that makes sense. no matter how many times I run the operation, it's one of those numbers. I didn't think that made sense

**Comment by ajoshua01** [comment]
oh I understand. Yeah because I'm not actually randomly selecting the distances. I'm using either the source or destination node value as the distance between the two. So in this version of the Graph the distance will always be one of the two numbers. If we want, I can make it a random number in the next version.

**Comment by KyleAlt2021** [comment]
Oh, duh. I should've double-checked I suppose. Yeah, we should switch it to a random number real quick. Problem solved!
